<a href="https://colab.research.google.com/github/Moatemri/machine-learning-zoomcamp/blob/main/01-Intro/homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [81]:
import pandas as pd
import numpy as np

In [59]:
df=pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [ ]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [24]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [26]:
df['fuel_type'].nunique()

3

In [32]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [33]:
df['fuel_efficiency_mpg'].max()

41.2

In [60]:
df['horsepower'].mean()

np.float64(254.44601556505535)

In [61]:
df['horsepower'].mode()[0]

np.float64(252.0)

In [62]:
df['horsepower']=df['horsepower'].fillna(252.0)

In [63]:
df['horsepower'].mean()

np.float64(254.2315)

In [78]:
X= df[df['origin'] == 'Asia'][['vehicle_weight','model_year']].head(7).to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [88]:
XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [83]:
Y=np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
Y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [98]:
XTX_inv = np.linalg.inv(XTX)
W = (XTX_inv.dot(X.T)).dot(Y)
W.sum()

np.float64(0.36919696904925486)